{
  "swagger" : "2.0",
  "info" : {
    "description" : "Beautiful Pyems é uma aplicação desenvolvida em Python com o microframework Flask.  Seu objetivo principal é fornecer poemas quando for requisitado. A base para sua criação foi uma aplicação ETL que acessa o site https://www.escritas.org/pt/ e efetua uma raspagem de dados obtendo grandes volumes de documentos que são armazenados no MongoDB.",
    "version" : "1.0.0",
    "title" : "Beautiful Pyems",
    "contact" : {
      "name" : "Rodrigo Siliunas",
      "email" : "rodrigo.siliunas98@outlook.com"
    }
  },
  "paths" : { }
}